#!/usr/bin/perl

use strict;
use warnings;

use IO::All;

my $sig = io()->file($ENV{HOME}."/.signature")->slurp();

my ($quote) = ($sig =~ m{(([^\n]*\w[^\n]*\n)+)\z}ms);

my @resource_lines =
(
    qq{Best Introductory Programming Language - http://shlom.in/intro-lang},
    qq{First stop for Perl beginners - http://perl-begin.org/},
    qq{Freecell Solver - http://fc-solve.berlios.de/},
    qq{Funny Anti-Terrorism Story - http://shlom.in/enemy}, # The Enemy and How I Helped to Fight it.
    qq{http://www.shlomifish.org/humour/ways_to_do_it.html},
    qq{"Humanity" - Parody of Modern Life - http://shlom.in/humanity},
    qq{Interview with Ben Collins-Sussman - http://shlom.in/sussman},
    qq{List of Portability Libraries - http://shlom.in/port-libs},
    qq{My Aphorisms - http://www.shlomifish.org/humour.html},
    qq{Original Riddles - http://www.shlomifish.org/puzzles/},
    qq{Optimising Code for Speed - http://shlom.in/optimise},
    qq{Parody on "The Fountainhead" - http://shlom.in/towtf},
    qq{Rethinking CPAN - http://shlom.in/rethinking-cpan},
    qq{Stop Using MSIE - http://www.shlomifish.org/no-ie/},
    qq{"Star Trek: We, the Living Dead" - http://shlom.in/st-wtld},
    qq{The Case for File Swapping - http://shlom.in/file-swap},
    qq{"The Human Hacking Field Guide" - http://shlom.in/hhfg},
    qq{Understand what Open Source is - http://shlom.in/oss-fs},
    qq{What does "Zionism" mean? - http://shlom.in/def-zionism},
    qq{What Makes Software Apps High Quality -  http://shlom.in/sw-quality},
    qq{Why I Love Perl - http://shlom.in/joy-of-perl},
);

my $line = $resource_lines[rand(@resource_lines)];

my $text = <<"EOF";
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
$line

$quote
Please reply to list if it's a mailing list post - http://shlom.in/reply .
EOF

chomp($text);
print $text;
