#!/usr/bin/perl

use strict;
use warnings;

use Math::BigInt ( try => 'GMP' );

use utf8;

use File::Spec::Functions qw( catpath splitpath rel2abs );

sub _myrand
{
    my ($max) = @_;

    if ( open my $fh, '<:raw', '/dev/urandom' )
    {
        my $n = Math::BigInt->new(0);

        my $buf = '';
        read( $fh, $buf, 16 );

        for my $c ( split //, $buf )
        {
            $n = ( ( $n << 8 ) | ord($c) );
        }

        close($fh);
        return ( $n % $max );
    }
    else
    {
        return int( rand($max) );
    }
}

sub _pick
{
    my ($aref) = @_;

    return $aref->[ _myrand( scalar(@$aref) ) ];
}

my $script_dir = catpath( ( splitpath( rel2abs $0 ) )[ 0, 1 ] );

=head1 Rejects

No longer relevant or of interest:

    qq{Rethinking CPAN - https://shlom.in/rethinking-cpan},
    qq{Stop Using MSIE - https://www.shlomifish.org/no-ie/},

=cut

my @resource_lines = (
    qq{Apple Inc. is Evil - https://www.shlomifish.org/open-source/anti/apple/},
    qq{Beginners Site for the Vim text editor - https://vim.begin-site.org/},
    qq{Best Introductory Programming Language - https://shlom.in/intro-lang},
    qq{Buffy Factoids - https://www.shlomifish.org/humour/bits/facts/Buffy/},
    qq{Chuck Norris/etc. Facts - https://www.shlomifish.org/humour/bits/facts/},
    qq{Emma Watson Factoids - https://shlom.in/emwatson-facts},
qq{Escape from GNU Autohell - https://www.shlomifish.org/open-source/anti/autohell/},
    qq{First stop for Perl beginners - https://perl-begin.org/},
qq{Free (Creative Commons) Music Downloads, Reviews and more - https://jamendo.com/},
    qq{Freecell Solver - https://fc-solve.shlomifish.org/},
    qq{Funny Anti-Terrorism Story - https://shlom.in/enemy}
    ,    # The Enemy and How I Helped to Fight it.
    qq{Humanity - Parody of Modern Life - https://shlom.in/humanity},
    qq{Interview with Ben Collins-Sussman - https://shlom.in/sussman},
    qq{Let’s talk about restores instead of backups - https://is.gd/WatQqu},
    qq{List of Graphics Apps - https://shlom.in/graphics},
    qq{List of Networking Clients - https://shlom.in/net-clients},
    qq{List of Portability Libraries - https://shlom.in/port-libs},
    qq{List of Text Editors and IDEs - https://shlom.in/IDEs},
    qq{List of Text Processing Tools - https://shlom.in/text-proc},
    qq{My Aphorisms - https://www.shlomifish.org/humour.html},
    qq{My Favourite FOSS - https://www.shlomifish.org/open-source/favourite/},
    qq{My Photos - https://www.flickr.com/photos/shlomif/},
    qq{NSA Factoids - https://www.shlomifish.org/humour/bits/facts/NSA/},
    qq{Optimising Code for Speed - https://shlom.in/optimise},
    qq{Original Riddles - https://www.shlomifish.org/puzzles/},
    qq{Parody of "The Fountainhead" - https://shlom.in/towtf},
    qq{Perl Elems to Avoid - https://perl-begin.org/tutorials/bad-elements/},
    qq{Perl Humour - https://perl-begin.org/humour/},
    qq{Selina Mandrake - The Slayer (Buffy parody) - https://shlom.in/selina},
    qq{Star Trek: “We, the Living Dead” - https://shlom.in/st-wtld},
    qq{Summer Glau Facts - https://shlom.in/sglau-facts},
    qq{The Case for File Swapping - https://shlom.in/file-swap},
    qq{The Human Hacking Field Guide - https://shlom.in/hhfg},
    qq{UNIX Fortune Cookies - https://www.shlomifish.org/humour/fortunes/},
    qq{Understand what Open Source is - https://shlom.in/oss-fs},
    qq{What Makes Software Apps High Quality -  https://shlom.in/sw-quality},
    qq{What does “Zionism” mean? - https://shlom.in/def-zionism},
    qq{Why I Love Perl - https://shlom.in/joy-of-perl},
qq{https://ccmixter.org/files/destinazione_altrove/49997 - “Paint The Sky”},
    qq{https://is.gd/KNvczZ - The FSF Announces New Versions of the GPL},
    qq{https://is.gd/htwEXQ - Integrating GNU Guile into GNU coreutils},
    qq{https://is.gd/i5eMQd - Emma Watson’s Interview for a Software Dev Job},
qq{https://shlomifishswiki.branchable.com/Encourage_criticism_and_try_to_get_offended/},
    qq{https://shlomifishswiki.branchable.com/Self-Sufficiency/},
    qq{https://www.shlomifish.org/humour/Summerschool-at-the-NSA/},
qq{https://www.shlomifish.org/humour/bits/Can-I-SCO-Now/ - “Can I SCO Now?”},
    qq{https://www.shlomifish.org/humour/bits/Google-Discontinues-Services/},
    qq{https://www.shlomifish.org/humour/bits/New-versions-of-the-GPL/},
    qq{https://www.shlomifish.org/humour/bits/facts/Emma-Watson/},
    qq{https://www.shlomifish.org/humour/bits/facts/Summer-Glau/},
    qq{https://www.shlomifish.org/humour/bits/facts/Taylor-Swift/},
    qq{https://www.shlomifish.org/humour/ways_to_do_it.html},
    qq{https://www.shlomifish.org/lecture/C-and-CPP/bad-elements/},
    qq{https://www.shlomifish.org/open-source/projects/fortune-mod/},
    qq{https://www.shlomifish.org/open-source/resources/tech-tips/},
    qq{https://youtu.be/KxGRhd_iWuE - Never Give Up!!},
    qq{https://youtu.be/xZLwtc9x4yA - Anime in Real Life!! (Parody)},
    qq{https://github.com/shlomif/Freenode-programming-channel-FAQ},
    qq{https://github.com/shlomif/PySolFC - open source Solitaire games},
    qq{https://github.com/shlomif/shlomif-computer-settings/ - my dotfiles},
    qq{https://github.com/shlomif/validate-your-html - Validate Your HTML},
    qq{https://github.com/shlomif/what-you-should-know-about-automated-testing},
    qq{https://github.com/sindresorhus/awesome - curated list of lists},
    qq{https://is.gd/MQHVF3 - The Atom Text Editor edits a 2,000,001B file},
    qq{https://youtu.be/GoEn1YfYTBM - Tiffany Alvord - “Fall Together”},
    qq{https://youtu.be/n6KAGqjdmsk - “Hurt Me Tomorrow”},
    qq{“So, who the hell is Qoheleth?” - https://shlom.in/qoheleth},
);

my $line = _pick( \@resource_lines );

sub _slurp
{
    my $filename = shift;

    open my $in, '<:encoding(utf8)', $filename
        or die "Cannot open '$filename' for slurping - $!";

    local $/;
    my $contents = <$in>;

    close($in);

    return $contents;
}

my $quotes_text = _slurp("$script_dir/shlomif-sig-quotes.txt");

my @quotes = grep { /\S/ } split( /^\n*%\n*$/ms, $quotes_text );

my $quote = _pick( \@quotes );

$quote =~ s{\n+\z}{}ms;
$quote =~ s{\A\n+}{}ms;

binmode STDOUT, ":utf8";
print <<"EOF";

Shlomi Fish       https://www.shlomifish.org/
$line

$quote

Please reply to list if it's a mailing list post - https://shlom.in/reply .
EOF
